
spring:
  mvc:
    view:
      suffix: .html
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test0506?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mapping/*.xml
logging:
  file: springlog.log